name: swapi_flutter_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_carousel_widget: ^2.2.0
  flutter_local_notifications: ^16.3.2
  flutter_markdown: ^0.6.20+1
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^1.0.8
  gap: ^3.0.1
  geolocator: ^11.0.0
  get_it: ^7.6.7
  google_directions_api: ^0.10.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.6.0
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  timezone: ^0.9.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatar/
    - assets/icon/
    - assets/lottie/
